# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_workWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputs = QtWidgets.QTabWidget(self.widget)
        self.inputs.setObjectName("inputs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.i_number = QtWidgets.QLineEdit(self.tab_4)
        self.i_number.setObjectName("i_number")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.i_number)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setObjectName("comboBox_7")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setObjectName("comboBox_8")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.i_index = QtWidgets.QComboBox(self.tab_4)
        self.i_index.setEditable(True)
        self.i_index.setObjectName("i_index")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.i_index)
        self.i_date = QtWidgets.QDateEdit(self.tab_4)
        self.i_date.setObjectName("i_date")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.i_date)
        self.horizontalLayout_4.addLayout(self.formLayout_6)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_4)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.tab_4)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateEdit_3)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_10.setEditable(True)
        self.comboBox_10.setObjectName("comboBox_10")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_10)
        self.verticalLayout_3.addLayout(self.formLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.horizontalLayout_8.setStretch(0, 3)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.tableView = QtWidgets.QTableView(self.tab_5)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_7.addWidget(self.tableView)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        self.inputs.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label = QtWidgets.QLabel(self.tab_6)
        self.Label.setObjectName("Label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.Label_2 = QtWidgets.QLabel(self.tab_6)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.tab_6)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Label_3 = QtWidgets.QLabel(self.tab_6)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.Label_4 = QtWidgets.QLabel(self.tab_6)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.comboBox = QtWidgets.QComboBox(self.tab_6)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.Label_9 = QtWidgets.QLabel(self.tab_6)
        self.Label_9.setObjectName("Label_9")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.tab_6)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit_4)
        self.dateEdit_5 = QtWidgets.QDateEdit(self.tab_6)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateEdit_5)
        self.horizontalLayout_6.addLayout(self.formLayout_3)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.Label_7 = QtWidgets.QLabel(self.tab_6)
        self.Label_7.setObjectName("Label_7")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_11.setEditable(True)
        self.comboBox_11.setObjectName("comboBox_11")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.Label_8 = QtWidgets.QLabel(self.tab_6)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_12.setEditable(True)
        self.comboBox_12.setObjectName("comboBox_12")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.Label_5 = QtWidgets.QLabel(self.tab_6)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.Label_6 = QtWidgets.QLabel(self.tab_6)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.horizontalLayout_6.addLayout(self.formLayout_5)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_6.addWidget(self.label_27)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_6.addWidget(self.textEdit_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_9.addWidget(self.pushButton_6)
        self.horizontalLayout_9.setStretch(0, 3)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.tableView_2 = QtWidgets.QTableView(self.tab_7)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_8.addWidget(self.tableView_2)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.horizontalLayout_3.addWidget(self.tabWidget_3)
        self.inputs.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.inputs)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.inputs.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Документы"))
        self.label_13.setText(_translate("MainWindow", "№ входящего:"))
        self.label_14.setText(_translate("MainWindow", "Дата входящего:"))
        self.label_15.setText(_translate("MainWindow", "Отправитель:"))
        self.label_16.setText(_translate("MainWindow", "Получено:"))
        self.label_17.setText(_translate("MainWindow", "Индекс:"))
        self.label_5.setText(_translate("MainWindow", "№ исходящего:"))
        self.label_6.setText(_translate("MainWindow", "Дата исходящего"))
        self.label_7.setText(_translate("MainWindow", "Получатель:"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Исполнитель:</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Дата контроля:"))
        self.label_19.setText(_translate("MainWindow", "Содержание:"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\"><br /></span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Резолюция:"))
        self.pushButton_2.setText(_translate("MainWindow", "Очистить"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Добавить/изменить"))
        self.pushButton_5.setText(_translate("MainWindow", "Найти"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Список"))
        self.inputs.setTabText(self.inputs.indexOf(self.tab), _translate("MainWindow", "Входящие"))
        self.Label.setText(_translate("MainWindow", "Индекс:"))
        self.Label_2.setText(_translate("MainWindow", "№ исходящего:"))
        self.Label_3.setText(_translate("MainWindow", "Дата исходящего"))
        self.Label_4.setText(_translate("MainWindow", "На № входящего:"))
        self.Label_9.setText(_translate("MainWindow", "Дата отправления:"))
        self.Label_7.setText(_translate("MainWindow", "ФИО исполнителя:"))
        self.Label_8.setText(_translate("MainWindow", "Отправлено:"))
        self.Label_5.setText(_translate("MainWindow", "Получатель:"))
        self.Label_6.setText(_translate("MainWindow", "ФИО получателя:"))
        self.label_27.setText(_translate("MainWindow", "Содержание:"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\"><br /></span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_4.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Добавить/изменить"))
        self.pushButton_6.setText(_translate("MainWindow", "Найти"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Список"))
        self.inputs.setTabText(self.inputs.indexOf(self.tab_3), _translate("MainWindow", "Исходящие"))
        self.menu.setTitle(_translate("MainWindow", "Настройки"))
